// <auto-generated />
namespace ConstructionLK.Migrations.ConstructionLKContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddItemMainCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddItemMainCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201711061349131_AddItemMainCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
